
import React from 'react';
import { StoreName, CampaignTheme, Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  fr: {
    searchPlaceholder: "Chercher un produit, une marque...",
    smartSuggestions: "Suggestions intelligentes",
    noResults: "Aucun résultat",
    reset: "Réinitialiser",
    cart: "Panier",
    myOrders: "Mes Roadmaps",
    saved: "Favoris",
    compare: "Comparer",
    save: "Sauver",
    selected: "Sélectionné",
    addToCart: "Ajouter",
    bestOffer: "Meilleure offre",
    reportError: "Signaler",
    compareAll: "Comparer Tout",
    login: "Connexion",
    logout: "Déconnexion",
    history: "Historique",
    admin: "Console Admin",
    filterBy: "Filtrer",
    sortBy: "Trier",
    relevance: "Pertinence",
    priceAsc: "Prix croissant",
    priceDesc: "Prix décroissant",
    nameAsc: "Nom (A-Z)",
    nameDesc: "Nom (Z-A)",
    magicImport: "Importation IA",
    magicPlaceholder: "Collez votre liste...",
    convertCart: "Convertir en Panier",
    events: "Packs & Promos",
    popularProducts: "Produits populaires",
    itemsFound: "articles",
    total: "Total",
    validate: "Commander",
    standardMaroc: "Standard Maroc",
    freshPrice: "Prix Frais",
    verify: "Vérifier",
    optimize: "Optimiser",
    roadmap: "Ma Roadmap",
    finishShopping: "Terminé",
    step: "Étape",
    toCollect: "à prendre",
    emptyCart: "Panier vide",
    categoryAll: "Toutes les catégories",
    authSubtitle: "Votre budget, maîtrisé.",
    optimizationTitle: "Optimisation",
    deliveryMode: "Mode de Livraison",
    homeDelivery: "Livraison à domicile",
    privateRoadmap: "Itinéraire privé (GPS)",
    paymentMethod: "Mode de Paiement",
    cod: "Cash à la livraison",
    cmi: "Carte Bancaire (CMI)",
    promoExpires: "Expire dans",
    adminProducts: "Gestion Stock",
    adminStats: "Statistiques",
    addProduct: "Ajouter un produit",
    editProduct: "Modifier",
    saveChanges: "Enregistrer",
    promoCode: "Code Promo",
    apply: "Appliquer",
    invalidCode: "Code invalide",
    promoDiscount: "Remise Promo",
    reportSent: "Signalement envoyé. Merci !",
    addComment: "Ajouter un commentaire...",
    myProfile: "Mon Profil",
    personalInfo: "Infos Personnelles",
    personalStats: "Mes Statistiques",
    totalSavings: "Économies Jaybi",
    ordersPlaced: "Roadmaps créées",
    favoriteBrand: "Marque Préférée",
    itemsSaved: "Articles sauvés",
    updateProfile: "Mettre à jour mon profil",
    deleteAccount: "Supprimer mon compte",
    changePassword: "Modifier mon mot de passe",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    sendCode: "Recevoir le code par email",
    enterCode: "Code de vérification",
    verifyAndChange: "Vérifier et modifier",
    codeSentTo: "Code envoyé à",
    passwordChanged: "Mot de passe modifié avec succès !",
    share: "Partager",
    print: "Imprimer",
    legalNotice: "Mentions Légales",
    privacyPolicy: "Confidentialité",
    sponsored: "Sponsorisé",
    copyright: "© 2025 Jaybi. Tous droits réservés.",
    verifyEmailTitle: "Vérifiez votre email",
    verificationSubtitle: "Saisissez le code à 6 chiffres pour continuer.",
    confirmIdentity: "Confirmer mon identité",
    wrongCode: "Code de vérification incorrect.",
    continueWithGoogle: "Continuer avec Google",
    orByEmail: "Ou par email",
    createAccount: "Créer mon compte",
    alreadyMember: "Déjà membre ? Se connecter",
    signUpPrompt: "Nouveau ? Créer un compte",
    modifyEmailOrCancel: "Modifier l'email ou annuler",
    identifying: "Identification...",
    verifying: "Vérification...",
    emailPlaceholder: "Email (ex: admin@qayess.io)",
    passwordPlaceholder: "Mot de passe",
    codePlaceholder: "—— ——",
    currencySuffix: "DH"
  },
  en: {
    searchPlaceholder: "Search product, brand...",
    smartSuggestions: "Smart suggestions",
    noResults: "No results",
    reset: "Reset",
    cart: "Cart",
    myOrders: "My Roadmaps",
    saved: "Wishlist",
    compare: "Compare",
    save: "Save",
    selected: "Selected",
    addToCart: "Add",
    bestOffer: "Best offer",
    reportError: "Report",
    compareAll: "Compare All",
    login: "Login",
    logout: "Logout",
    history: "History",
    admin: "Admin Console",
    filterBy: "Filter",
    sortBy: "Sort",
    relevance: "Relevance",
    priceAsc: "Price Low-High",
    priceDesc: "Price High-Low",
    nameAsc: "Name A-Z",
    nameDesc: "Name Z-A",
    magicImport: "AI Import",
    magicPlaceholder: "Paste list...",
    convertCart: "Convert",
    events: "Packs & Deals",
    popularProducts: "Popular items",
    itemsFound: "items",
    total: "Total",
    validate: "Checkout",
    standardMaroc: "Morocco Standard",
    freshPrice: "Fresh Price",
    verify: "Verify",
    optimize: "Optimize",
    roadmap: "Roadmap",
    finishShopping: "Done",
    step: "Step",
    toCollect: "to collect",
    emptyCart: "Cart is empty",
    categoryAll: "All categories",
    authSubtitle: "Your budget, mastered.",
    optimizationTitle: "Optimization",
    deliveryMode: "Delivery Mode",
    homeDelivery: "Home Delivery",
    privateRoadmap: "Private Route (GPS)",
    paymentMethod: "Payment Method",
    cod: "Cash on delivery",
    cmi: "Credit Card (CMI)",
    promoExpires: "Expires in",
    adminProducts: "Stock Management",
    adminStats: "Statistics",
    addProduct: "Add product",
    editProduct: "Edit",
    saveChanges: "Save changes",
    promoCode: "Promo Code",
    apply: "Apply",
    invalidCode: "Invalid Code",
    promoDiscount: "Promo Discount",
    reportSent: "Report sent. Thank you!",
    addComment: "Add a comment...",
    myProfile: "My Profile",
    personalInfo: "Personal Info",
    personalStats: "My Statistics",
    totalSavings: "Jaybi Savings",
    ordersPlaced: "Roadmaps Created",
    favoriteBrand: "Favorite Brand",
    itemsSaved: "Saved Items",
    updateProfile: "Update Profile",
    deleteAccount: "Delete Account",
    changePassword: "Change Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    sendCode: "Send code to email",
    enterCode: "Verification Code",
    verifyAndChange: "Verify and change",
    codeSentTo: "Code sent to",
    passwordChanged: "Password successfully updated!",
    share: "Share",
    print: "Print",
    legalNotice: "Legal Notice",
    privacyPolicy: "Privacy Policy",
    sponsored: "Sponsored",
    copyright: "© 2025 Jaybi. All rights reserved.",
    verifyEmailTitle: "Verify your email",
    verificationSubtitle: "Enter the 6-digit code to continue.",
    confirmIdentity: "Confirm my identity",
    wrongCode: "Incorrect verification code.",
    continueWithGoogle: "Continue with Google",
    orByEmail: "Or by email",
    createAccount: "Create my account",
    alreadyMember: "Already a member? Log in",
    signUpPrompt: "New here? Create an account",
    modifyEmailOrCancel: "Edit email or cancel",
    identifying: "Identifying...",
    verifying: "Verifying...",
    emailPlaceholder: "Email (e.g. admin@qayess.io)",
    passwordPlaceholder: "Password",
    codePlaceholder: "—— ——",
    currencySuffix: "MAD"
  },
  es: {
    searchPlaceholder: "Buscar producto, marca...",
    smartSuggestions: "Sugerencias inteligentes",
    noResults: "Sin resultados",
    reset: "Reiniciar",
    cart: "Carrito",
    myOrders: "Mis Hojas de Ruta",
    saved: "Favoritos",
    compare: "Comparar",
    save: "Guardar",
    selected: "Seleccionado",
    addToCart: "Añadir",
    bestOffer: "Mejor oferta",
    reportError: "Informar",
    compareAll: "Comparar todo",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    history: "Historial",
    admin: "Consola de administración",
    filterBy: "Filtrar",
    sortBy: "Ordenar",
    relevance: "Relevancia",
    priceAsc: "Precio Bajo-Alto",
    priceDesc: "Precio Alto-Bajo",
    nameAsc: "Nombre A-Z",
    nameDesc: "Nombre Z-A",
    magicImport: "Importación IA",
    magicPlaceholder: "Pegar lista...",
    convertCart: "Convertir",
    events: "Packs y Ofertas",
    popularProducts: "Productos populares",
    itemsFound: "artículos",
    total: "Total",
    validate: "Pagar",
    standardMaroc: "Estándar Marruecos",
    freshPrice: "Precio Fresco",
    verify: "Verificar",
    optimize: "Optimizar",
    roadmap: "Ruta de compras",
    finishShopping: "Hecho",
    step: "Paso",
    toCollect: "por recoger",
    emptyCart: "Carrito vacío",
    categoryAll: "Todas las categorías",
    authSubtitle: "Tu presupuesto, dominado.",
    optimizationTitle: "Optimización",
    deliveryMode: "Modo de entrega",
    homeDelivery: "Entrega a domicilio",
    privateRoadmap: "Ruta privada (GPS)",
    paymentMethod: "Método de pago",
    cod: "Pago contra entrega",
    cmi: "Tarjeta de crédito (CMI)",
    promoExpires: "Expira en",
    adminProducts: "Gestión de stock",
    adminStats: "Estadísticas",
    addProduct: "Añadir producto",
    editProduct: "Editar",
    saveChanges: "Guardar cambios",
    promoCode: "Código promocional",
    apply: "Aplicar",
    invalidCode: "Código inválido",
    promoDiscount: "Descuento promo",
    reportSent: "Reporte enviado. ¡Gracias!",
    addComment: "Añadir un comentario...",
    myProfile: "Mi Perfil",
    personalInfo: "Información Personal",
    personalStats: "Mis Estadísticas",
    totalSavings: "Ahorros Jaybi",
    ordersPlaced: "Rutas Creadas",
    favoriteBrand: "Marca Favorita",
    itemsSaved: "Artículos Guardados",
    updateProfile: "Actualizar Perfil",
    deleteAccount: "Eliminar Cuenta",
    changePassword: "Cambiar Contraseña",
    newPassword: "Nueva Contraseña",
    confirmPassword: "Confirmar Contraseña",
    sendCode: "Enviar código por email",
    enterCode: "Código de Verificación",
    verifyAndChange: "Verificar y cambiar",
    codeSentTo: "Código enviado a",
    passwordChanged: "¡Contraseña actualizada con éxito!",
    share: "Compartir",
    print: "Imprimir",
    legalNotice: "Aviso Legal",
    privacyPolicy: "Privacidad",
    sponsored: "Patrocinado",
    copyright: "© 2025 Jaybi. Todos los derechos reservados.",
    verifyEmailTitle: "Verifica tu email",
    verificationSubtitle: "Ingresa el código de 6 dígitos para continuar.",
    confirmIdentity: "Confirmar mi identidad",
    wrongCode: "Código de verificación incorrecto.",
    continueWithGoogle: "Continuar con Google",
    orByEmail: "O por correo",
    createAccount: "Crear mi cuenta",
    alreadyMember: "¿Ya miembro? Iniciar sesión",
    signUpPrompt: "¿Nuevo? Crear una cuenta",
    modifyEmailOrCancel: "Editar correo o cancelar",
    identifying: "Identificando...",
    verifying: "Verificando...",
    emailPlaceholder: "Correo (ej: admin@qayess.io)",
    passwordPlaceholder: "Contraseña",
    codePlaceholder: "—— ——",
    currencySuffix: "MAD"
  },
  zh: {
    searchPlaceholder: "搜索产品，品牌...",
    smartSuggestions: "智能建议",
    noResults: "无结果",
    reset: "重置",
    cart: "购物车",
    myOrders: "我的路线图",
    saved: "收藏夹",
    compare: "比较",
    save: "保存",
    selected: "已选择",
    addToCart: "添加",
    bestOffer: "最佳报价",
    reportError: "举报",
    compareAll: "全部比较",
    login: "登录",
    logout: "登出",
    history: "历史",
    admin: "管理控制台",
    filterBy: "过滤",
    sortBy: "排序",
    relevance: "相关性",
    priceAsc: "价格从低到高",
    priceDesc: "价格从高到低",
    nameAsc: "名称 A-Z",
    nameDesc: "名称 Z-A",
    magicImport: "AI 导入",
    magicPlaceholder: "粘贴列表...",
    convertCart: "转换",
    events: "礼包与优惠",
    popularProducts: "热门产品",
    itemsFound: "件商品",
    total: "总计",
    validate: "结账",
    standardMaroc: "摩洛哥标准",
    freshPrice: "新鲜价格",
    verify: "核实",
    optimize: "优化",
    roadmap: "购物路线",
    finishShopping: "完成",
    step: "步骤",
    toCollect: "待领取",
    emptyCart: "购物车为空",
    categoryAll: "所有类别",
    authSubtitle: "掌控您的预算",
    optimizationTitle: "优化",
    deliveryMode: "配送方式",
    homeDelivery: "送货上门",
    privateRoadmap: "私人路线 (GPS)",
    paymentMethod: "支付方式",
    cod: "货到付款",
    cmi: "银行卡 (CMI)",
    promoExpires: "过期时间",
    adminProducts: "库存管理",
    adminStats: "统计数据",
    addProduct: "添加产品",
    editProduct: "编辑",
    saveChanges: "保存更改",
    promoCode: "促销代码",
    apply: "应用",
    invalidCode: "代码无效",
    promoDiscount: "促销折扣",
    reportSent: "报告已发送。谢谢！",
    addComment: "添加评论...",
    myProfile: "我的档案",
    personalInfo: "个人信息",
    personalStats: "我的统计数据",
    totalSavings: "Jaybi 节省",
    ordersPlaced: "已创建路线",
    favoriteBrand: "最喜欢的品牌",
    itemsSaved: "收藏的商品",
    updateProfile: "更新档案",
    deleteAccount: "删除账户",
    changePassword: "修改密码",
    newPassword: "新密码",
    confirmPassword: "确认新密码",
    sendCode: "发送验证码到邮箱",
    enterCode: "验证码",
    verifyAndChange: "验证并修改",
    codeSentTo: "验证码已发送至",
    passwordChanged: "密码修改成功！",
    share: "分享",
    print: "打印",
    legalNotice: "法律声明",
    privacyPolicy: "隐私政策",
    sponsored: "赞助",
    copyright: "© 2025 Jaybi. 版权所有。",
    verifyEmailTitle: "验证您的电子邮件",
    verificationSubtitle: "输入 6 位数代码以继续。",
    confirmIdentity: "确认我的身份",
    wrongCode: "验证码错误。",
    continueWithGoogle: "使用 Google 继续",
    orByEmail: "或使用电子邮件",
    createAccount: "创建我的账户",
    alreadyMember: "已是会员？登录",
    signUpPrompt: "新用户？创建账户",
    modifyEmailOrCancel: "修改邮箱或取消",
    identifying: "识别中...",
    verifying: "验证中...",
    emailPlaceholder: "邮箱（例如 admin@qayess.io）",
    passwordPlaceholder: "密码",
    codePlaceholder: "—— ——",
    currencySuffix: "MAD"
  },
  ar: {
    searchPlaceholder: "ابحث عن منتج، علامة تجارية...",
    smartSuggestions: "اقتراحات ذكية",
    noResults: "لا توجد نتائج",
    reset: "إعادة تعيين",
    cart: "السلة",
    myOrders: "خرائطي",
    saved: "المفضلة",
    compare: "مقارنة",
    save: "حفظ",
    selected: "مختار",
    addToCart: "إضافة",
    bestOffer: "أفضل عرض",
    reportError: "تبليغ",
    compareAll: "مقارنة الكل",
    login: "دخول",
    logout: "خروج",
    history: "السجل",
    admin: "لوحة التحكم",
    filterBy: "تصفية",
    sortBy: "ترتيب",
    relevance: "الأهمية",
    priceAsc: "السعر: من الأقل",
    priceDesc: "السعر: من الأكثر",
    nameAsc: "الاسم: أ-ي",
    nameDesc: "الاسم: ي-أ",
    magicImport: "استيراد ذكي",
    magicPlaceholder: "الصق القائمة...",
    convertCart: "تحويل",
    events: "عروض وباقات",
    popularProducts: "المنتجات الشائعة",
    itemsFound: "منتج",
    total: "المجموع",
    validate: "تأكيد الطلب",
    standardMaroc: "معيار مغربي",
    freshPrice: "سعر طري",
    verify: "تحقق",
    optimize: "تحسين",
    roadmap: "خريطة التسوق",
    finishShopping: "تم",
    step: "خطوة",
    toCollect: "للجمع",
    emptyCart: "السلة فارغة",
    categoryAll: "جميع الفئات",
    authSubtitle: "تحكم في ميزانيتك",
    optimizationTitle: "تحسين",
    deliveryMode: "طريقة التوصيل",
    homeDelivery: "توصيل للمنزل",
    privateRoadmap: "خريطة خاصة",
    paymentMethod: "طريقة الأداء",
    cod: "الدفع عند الاستلام",
    cmi: "بطاقة بنكية (CMI)",
    promoExpires: "تنتهي في",
    adminProducts: "إدارة المخزون",
    adminStats: "إحصائيات",
    addProduct: "إضافة منتج",
    editProduct: "تعديل",
    saveChanges: "حفظ",
    promoCode: "رمز ترويجي",
    apply: "تطبيق",
    invalidCode: "رمز غير صالح",
    promoDiscount: "خصم ترويجي",
    reportSent: "تم إرسال التقرير. شكرا!",
    addComment: "أضف تعليقًا...",
    myProfile: "ملفي الشخصي",
    personalInfo: "المعلومات الشخصية",
    personalStats: "إحصائياتي",
    totalSavings: "توفيرات Jaybi",
    ordersPlaced: "الخرائط المنشأة",
    favoriteBrand: "الماركة المفضلة",
    itemsSaved: "العناصر المحفوظة",
    updateProfile: "تحديث الملف",
    deleteAccount: "حذف الحساب",
    changePassword: "تغيير كلمة المرور",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    sendCode: "إرسال الرمز للبريد",
    enterCode: "رمز التحقق",
    verifyAndChange: "تحقق وتغيير",
    codeSentTo: "تم إرسال الرمز إلى",
    passwordChanged: "تم تغيير كلمة المرور بنجاح!",
    share: "مشاركة",
    print: "طباعة",
    legalNotice: "إشعار قانوني",
    privacyPolicy: "سياسة الخصوصية",
    sponsored: "إعلان",
    copyright: "© 2025 Jaybi. جميع الحقوق محفوظة.",
    verifyEmailTitle: "تحقق من بريدك الإلكتروني",
    verificationSubtitle: "أدخل الرمز المكون من 6 أرقام للمتابعة.",
    confirmIdentity: "تأكيد هويتي",
    wrongCode: "رمز التحقق غير صحيح.",
    continueWithGoogle: "المتابعة باستخدام Google",
    orByEmail: "أو عبر البريد الإلكتروني",
    createAccount: "إنشاء حسابي",
    alreadyMember: "عضو بالفعل؟ تسجيل الدخول",
    signUpPrompt: "جديد؟ أنشئ حسابًا",
    modifyEmailOrCancel: "تعديل البريد أو إلغاء",
    identifying: "جارٍ التحقق...",
    verifying: "جارٍ التحقق...",
    emailPlaceholder: "البريد (مثال: admin@qayess.io)",
    passwordPlaceholder: "كلمة المرور",
    codePlaceholder: "—— ——",
    currencySuffix: "درهم"
  }
};

export const Icons = {
  Logo: (props?: any) => (
    <svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-10 h-10" {...props}>
      <defs>
        <linearGradient id="jaybiGradient" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor="#10B981" /> 
          <stop offset="100%" stopColor="#059669" />
        </linearGradient>
        <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
          <feDropShadow dx="2" dy="4" stdDeviation="3" floodColor="#000" floodOpacity="0.1"/>
        </filter>
      </defs>
      <rect x="10" y="10" width="80" height="80" rx="28" fill="white" stroke="#E2E8F0" strokeWidth="2" />
      <path 
        d="M65 25 V60 C65 73.8 53.8 85 40 85 C26.2 85 15 73.8 15 60" 
        stroke="url(#jaybiGradient)" 
        strokeWidth="12" 
        strokeLinecap="round" 
        strokeLinejoin="round"
        fill="none"
        filter="url(#shadow)"
      />
      <circle cx="65" cy="25" r="8" fill="#F59E0B" />
      <path d="M75 25 L85 15" stroke="#10B981" strokeWidth="3" strokeLinecap="round" opacity="0.6" />
      <path d="M80 35 L88 28" stroke="#10B981" strokeWidth="3" strokeLinecap="round" opacity="0.4" />
    </svg>
  ),
  Google: (props?: any) => <svg width="20" height="20" viewBox="0 0 48 48" {...props}><path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path><path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path><path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24s.92 7.54 2.56 10.78l7.97-6.19z"></path><path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path></svg>,
  Apple: (props?: any) => <svg width="20" height="20" viewBox="0 0 384 512" fill="currentColor" {...props}><path d="M318.7 268.7c-.2-36.7 16.4-64.4 50-84.8-18.8-26.9-47.2-41.7-84.7-44.6-35.5-2.8-74.3 20.7-88.5 20.7-15 0-49.4-19.7-76.4-19.7C63.3 141.2 4 184.8 4 273.5q0 39.3 14.4 81.2c12.8 36.7 59 126.7 107.2 125.2 25.2-.6 43-17.9 75.8-17.9 31.8 0 48.3 17.9 76.4 17.9 48.6-.7 90.4-82.5 102.6-119.3-65.2-30.7-61.7-90-61.7-91.9zm-56.6-164.2c27.3-32.4 24.8-61.9 24-72.5-24.1 1.4-52 16.4-67.9 34.9-17.5 19.8-27.8 44.3-25.6 71.9 26.1 2 49.9-11.4 69.5-34.3z"/></svg>,
  Microsoft: (props?: any) => <svg width="20" height="20" viewBox="0 0 23 23" {...props}><path fill="#f3f3f3" d="M0 0h23v23H0z"/><path fill="#f35325" d="M1 1h10v10H1z"/><path fill="#81bc06" d="M12 1h10v10H12z"/><path fill="#05a6f0" d="M1 12h10v10H1z"/><path fill="#ffba08" d="M12 12h10v10H12z"/></svg>,
  Facebook: (props?: any) => <svg width="20" height="20" viewBox="0 0 24 24" fill="#1877F2" {...props}><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.469h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.469h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>,
  Search: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>,
  Cart: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="8" cy="21" r="1"/><circle cx="19" cy="21" r="1"/><path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"/></svg>,
  Lightning: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>,
  Check: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M20 6 9 17l-5-5"/></svg>,
  Plus: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M5 12h14"/><path d="M12 5v14"/></svg>,
  Minus: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M5 12h14"/></svg>,
  ChevronRight: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m9 18 6-6-6-6"/></svg>,
  Stats: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><line x1="12" y1="20" x2="12" y2="10"/><line x1="18" y1="20" x2="18" y2="4"/><line x1="6" y1="20" x2="6" y2="16"/></svg>,
  Box: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><path d="m3.3 7 8.7 5 8.7-5"/><path d="M12 22V12"/></svg>,
  Heart: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/></svg>,
  Compare: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m15 12-3-3-3 3"/><path d="m9 12 3 3 3-3"/><path d="M12 3v18"/></svg>,
  Tag: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 2H2v10l9.29 9.29c.94.94 2.48.94 3.42 0l6.58-6.58c.94-.94.94-2.48 0-3.42L12 2Z"/><path d="M7 7h.01"/></svg>,
  Magic: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 3c.132 0 .263.051.362.153l7.293 7.293a.512.512 0 0 1 0 .724l-7.293 7.293a.512.512 0 0 1-.724 0L4.345 11.17a.512.512 0 0 1 0-.724l7.293-7.293A.512.512 0 0 1 12 3z"/><path d="M12 21v-3M12 6V3M6 12H3M21 12h-3"/></svg>,
  Edit: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>,
  Trash: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/><line x1="10" y1="11" x2="10" y2="17"/><line x1="14" y1="11" x2="14" y2="17"/></svg>,
  MessageSquare: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>,
  Bell: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>,
  User: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>,
  Lock: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>,
  Share: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" x2="15.42" y1="13.51" y2="17.49"/><line x1="15.41" x2="8.59" y1="6.51" y2="10.49"/></svg>,
  Printer: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M6 9V2h12v7"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><path d="M6 14h12v8H6z"/></svg>,
  Shield: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>,
  History: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M3 3v5h5"/><path d="M3.05 13A9 9 0 1 0 6 5.3L3 8"/><path d="M12 7v5l4 2"/></svg>,
  // --- Sync Center icons (Lucide-compatible paths) ---
  RefreshCw: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/><path d="M21 3v5h-5"/><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/><path d="M3 21v-5h5"/></svg>,
  Upload: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>,
  X: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>,
  Settings: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/></svg>,
  Activity: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2"/></svg>,
  Clock: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>,
  Package: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m7.5 4.27 9 5.15"/><path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><path d="m3.3 7 8.7 5 8.7-5"/><path d="M12 22V12"/></svg>,
  TrendingUp: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/></svg>,
  AlertCircle: (props?: any) => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
};

// --- Added Missing Exports ---

export const STORES: Record<StoreName, { logo: string; color: string }> = {
  [StoreName.MARJANE]: { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Marjane_Logo.svg/1200px-Marjane_Logo.svg.png', color: 'bg-blue-600' },
  [StoreName.MYMARKET]: { logo: '', color: 'bg-orange-600' },
  [StoreName.ASWAK]: { logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/c/ca/Aswak_Assalam_logo.png/1200px-Aswak_Assalam_logo.png', color: 'bg-green-700' },
  [StoreName.BIM]: { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Bim_Logo.svg/1200px-Bim_Logo.svg.png', color: 'bg-red-600' },
  [StoreName.CARREFOUR]: { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Carrefour_logo.svg/1200px-Carrefour_logo.svg.png', color: 'bg-blue-800' },
};

export const CATEGORY_VISUALS: Record<string, { emoji: string; color: string }> = {
  'Epicerie': { emoji: '🥫', color: 'from-amber-100 to-amber-200' },
  'Crèmerie': { emoji: '🥛', color: 'from-blue-100 to-blue-200' },
  'Boissons': { emoji: '🥤', color: 'from-cyan-100 to-cyan-200' },
  'Entretien': { emoji: '🧼', color: 'from-emerald-100 to-emerald-200' },
  'Fruits & Légumes': { emoji: '🍎', color: 'from-green-100 to-green-200' },
  'Boucherie': { emoji: '🥩', color: 'from-rose-100 to-rose-200' },
  'default': { emoji: '📦', color: 'from-slate-100 to-slate-200' }
};

export const THEME_CONFIG: Record<CampaignTheme, { label: string; color: string }> = {
  'standard': { label: 'Offre Standard', color: 'emerald' },
  'black-friday': { label: 'Black Friday', color: 'slate' },
  'white-friday': { label: 'White Friday', color: 'slate' },
  'halloween': { label: 'Halloween', color: 'orange' },
  'ramadan': { label: 'Ramadan Kareem', color: 'emerald' },
  'new-year': { label: 'Nouvel An', color: 'indigo' },
  'flash': { label: 'Vente Flash', color: 'rose' }
};
